'use client';

/**
 * The gate in front of the dashboard.
 *
 * Mandate cannot do anything without Midnight: the rules live in encrypted
 * local private state, and every action is a Compact proof generated by the
 * wallet. So the connection is not an optional first step to be skipped — it
 * is the only way in, and this screen says exactly what is required.
 *
 * There is deliberately no offline or simulated mode here. A screen that let
 * someone "try it" without a proof would be showing them a different product
 * from the one that protects their money.
 */

import { useState } from 'react';

import {
  FAUCET_URL,
  FEE_TOKEN,
  NETWORK_LABEL,
  SPEND_TOKEN,
  configuredContractAddress,
} from '../lib/network';
import { Field, Notice } from './components';
import { Arrow, Lock, Logo } from './icons';
import type { useSession } from './session';

type Session = ReturnType<typeof useSession>;

export function ConnectGate({ session }: { session: Session }) {
  const [password, setPassword] = useState('');
  const [attempted, setAttempted] = useState(false);

  const tooShort = password.length > 0 && password.length < 16;
  const registry = configuredContractAddress();
  const canConnect = password.length >= 16 && session.status !== 'connecting' && !!registry;

  async function submit(event: React.FormEvent) {
    event.preventDefault();
    setAttempted(true);
    await session.connect(password);
  }

  return (
    <div className="gate">
      <div className="gate-inner">
        <div className="gate-brand">
          <Logo size={40} />
          <div>
            <div className="gate-title">Mandate</div>
            <div className="gate-sub">Private spending authority on {NETWORK_LABEL}</div>
          </div>
        </div>

        <form className="card" onSubmit={submit}>
          <div className="card-head">
            <div>
              <div className="card-title">
                <span className="tile tile-sm">
                  <Lock size={16} />
                </span>
                Connect your wallet
              </div>
              <p className="card-sub">
                Every mandate is enforced by a Compact circuit on {NETWORK_LABEL}. Your wallet
                holds the keys, generates every zero-knowledge proof locally, and signs every
                transaction — this app never sees your keys or your rules, and cannot authorize a
                payment without a proof from your wallet.
              </p>
            </div>
          </div>

          {/*
            Fail loud, and before the password is typed: without a deployed
            registry there is no contract to prove against, so nothing this
            screen could do would work.
          */}
          {!registry && (
            <div style={{ marginBottom: 16 }}>
              <Notice tone="bad">
                <div>
                  <strong>No Mandate registry is configured.</strong> This deployment has no
                  contract address, so there is nothing to prove against and no mandate can be
                  created. Deploy one with <span className="mono">npm run contract:deploy</span>{' '}
                  and set <span className="mono">NEXT_PUBLIC_CONTRACT_ADDRESS</span>.
                </div>
              </Notice>
            </div>
          )}

          <Field
            label="Private-state password"
            hint="Encrypts your mandate rules and the secrets that authorize revoke and withdraw. At least 16 characters. It is never sent anywhere and cannot be recovered — store it somewhere safe."
          >
            <input
              type="password"
              value={password}
              autoComplete="new-password"
              placeholder="At least 16 characters"
              disabled={!registry}
              onChange={(e) => setPassword(e.target.value)}
            />
          </Field>

          {tooShort && (
            <div style={{ marginTop: 14 }}>
              <Notice tone="warn">
                That is {password.length} characters. The private-state store requires at least 16.
              </Notice>
            </div>
          )}

          {attempted && session.error && (
            <div style={{ marginTop: 14 }}>
              <Notice tone="bad">{session.error}</Notice>
            </div>
          )}

          <div className="btn-row" style={{ marginTop: 20 }}>
            <button type="submit" className="btn btn-primary btn-lg" disabled={!canConnect}>
              {session.status === 'connecting'
                ? (session.busyLabel ?? 'Connecting…')
                : 'Connect Lace wallet'}
              {session.status !== 'connecting' && <Arrow size={16} />}
            </button>
          </div>

          <div className="divider" />

          <div className="gate-reqs">
            <div className="label" style={{ marginBottom: 8 }}>
              What you need
            </div>
            <ul>
              <li>
                The <strong>Lace Midnight Preview</strong> extension, switched to{' '}
                <strong>{NETWORK_LABEL}</strong>. No other network is accepted.
              </li>
              <li>
                <strong>{SPEND_TOKEN}</strong> to fund a mandate escrow, and{' '}
                <strong>{FEE_TOKEN}</strong> to pay transaction fees.{' '}
                <a
                  href={FAUCET_URL}
                  target="_blank"
                  rel="noreferrer"
                  style={{ color: 'var(--violet)' }}
                >
                  Get test tokens from the faucet
                </a>
                .
              </li>
              <li>
                A deployed Mandate registry.{' '}
                {registry ? (
                  <span className="mono">{registry.slice(0, 18)}…</span>
                ) : (
                  'None is configured for this deployment.'
                )}
              </li>
            </ul>
          </div>
        </form>
      </div>
    </div>
  );
}
