/**
 * Domain model for Mandate.
 *
 * The shapes here are the *user-facing* view of a mandate. They are translated
 * into the Compact `MandateRules` struct by `toContractRules` in `./mandate`.
 *
 * Everything in `MandateSpec` and `MandateSecrets` is private: it lives in the
 * browser's local storage (or the agent's private state directory) and is never
 * transmitted to a server. Only the commitment derived from it reaches the chain.
 */

/** How often a rolling spend window resets. */
export type PeriodKind = 'none' | 'daily' | 'weekly';

export const PERIOD_SECONDS: Record<PeriodKind, bigint> = {
  none: 0n,
  daily: 86_400n,
  weekly: 604_800n,
};

/** The maximum number of allow-listed recipients a mandate can carry. */
export const MAX_ALLOWED_RECIPIENTS = 8;

/**
 * The complete, private rule set as the user authors it.
 *
 * Amounts are in the native token's smallest unit (see `NIGHT_DECIMALS`).
 * Timestamps are Unix seconds, matching the chain's own clock.
 */
export interface MandateSpec {
  /** Human label. Local only — never committed, never published. */
  label: string;
  maxTotalSpend: bigint;
  maxPerTransaction: bigint;
  validFrom: number;
  validUntil: number;
  period: PeriodKind;
  /** Ignored when `period` is 'none'. */
  periodLimit: bigint;
  /** Empty means the agent may pay any address. */
  allowedRecipients: string[];
  /** Hex-encoded public key of the one agent allowed to act. */
  agentPublicKey: string;
}

/**
 * The secrets that make a mandate usable. Losing these means losing the ability
 * to prove anything about the mandate — including the ability to withdraw.
 */
export interface MandateSecrets {
  /** Commitment opening. Without it the rules cannot be proven. */
  salt: string;
  /** Proves creator authority for revoke / withdraw. Never leaves the user. */
  creatorSecretKey: string;
  /**
   * The agent's secret key. Held by the creator only so the demo can hand it to
   * a local agent; in a real deployment this is generated by the agent and only
   * its public key is ever shared.
   */
  agentSecretKey: string;
}

/** A mandate as stored in the user's private state. */
export interface StoredMandate {
  /** 32-byte hex identifier, chosen at random on creation. */
  id: string;
  /**
   * The address that funded this mandate. The contract will only ever return
   * the unspent balance here, so it is fixed at creation and never editable.
   */
  creatorAddress: string;
  spec: MandateSpec;
  secrets: MandateSecrets;
  /** The commitment published on-chain, derived locally. */
  commitment: string;
  createdAt: number;
}

/** The public, on-chain record for a mandate. */
export interface MandateRecordView {
  id: string;
  commitment: string;
  agentPublicKey: string;
  creatorAuth: string;
  /** The only address the escrow can ever be returned to. */
  creatorAddress: string;
  escrow: bigint;
  deposited: bigint;
  spent: bigint;
  periodStart: bigint;
  periodSpent: bigint;
  actionCount: bigint;
  revoked: boolean;
}

/** A concrete action an agent proposes to take. */
export interface ProposedAction {
  mandateId: string;
  /** bech32m unshielded address of the payee. */
  recipient: string;
  amount: bigint;
  /** Reason the agent is acting, for the activity log. Local only. */
  memo?: string;
}

/** Identifiers for each rule the contract enforces. */
export type RuleId =
  | 'agent-identity'
  | 'not-revoked'
  | 'valid-from'
  | 'valid-until'
  | 'amount-positive'
  | 'per-transaction-limit'
  | 'total-spend-limit'
  | 'recipient-allow-list'
  | 'period-limit'
  | 'escrow-balance';

/** The outcome of checking one rule against a proposed action. */
export interface RuleCheck {
  rule: RuleId;
  label: string;
  passed: boolean;
  /** Present when `passed` is false: why, in the user's terms. */
  detail?: string;
}

/** Result of the agent's local pre-flight check. */
export interface PreCheckResult {
  authorized: boolean;
  checks: RuleCheck[];
  /** The first failing check, if any. */
  violation?: RuleCheck;
}

/** One entry in the agent activity log. */
export interface ActivityEntry {
  id: string;
  mandateId: string;
  at: number;
  recipient: string;
  amount: bigint;
  memo?: string;
  outcome: 'executed' | 'rejected-locally' | 'rejected-on-chain';
  /** Which rule stopped it, when it was stopped. */
  violatedRule?: RuleId;
  message: string;
  txId?: string;
}
